### PR TITLE
Support both PHP 7 and PHP <5.3

### PR DESCRIPTION
**Pull request by lengthofrope**
Hey there,

I've tried to fix the issues mentioned in #56. Hope you can merge them back into your repo.

Note: I've tested this with PHP 5.3, PHP 5.6 and PHP 7.0. Could not get my hands on PHP 5.2 at the moment, so it should be tested there as well.

Regards,
Bas

### CODE REVIEW

**Comment by YahnisElsts** [comment]
I've tested it briefly with PHP 5.2.9 and it seems to be working fine. I'll check a few more things later.

**Comment by lengthofrope** [comment]
Good to hear it seems to be working. Hopefully we can close issue #57 soon :)

**Comment by retlehs** [comment]
@YahnisElsts would it be possible to tag a new release? i'd like to include this plugin via composer and don't want to use the `dev-master` version for php 7 support

**Comment by YahnisElsts** [comment]
Sure. I've tagged `v3.1`.

**Comment by retlehs** [comment]
thank you 💙

**Pull request merged**
