### PR TITLE
Allows array as parameter argument and pulls service URI from file header

### PR DESCRIPTION
**Pull request by RichardCoffee**
Adds enhancement as per issue #349.

I'm sure more can be done with this, although it makes a good start.

### CODE REVIEW

**Comment by RichardCoffee** [comment]
Second commit fixes a logic error.  I was looking in the wrong array. :(

**Comment by YahnisElsts** [comment]
I feel like the method name `updateChecker` is too generic and it could be easily confused with `buildUpdateChecker`. Is there are a more descriptive name that we could use here? Maybe something like `buildFromHeader` (to indicate that pulls configuration data from the plugin/theme header)?

Also, I'd like to add the `EXTR_SKIP` flag to that `extract($args)` call. Technically, it's currently not necessary since the array is already filtered with `array_intersect_key`, but it could help prevent future bugs if the method becomes more complex over time.

**Comment by RichardCoffee** [comment]
> I feel like the method name `updateChecker` is too generic and it could be easily confused with `buildUpdateChecker`. Is there are a more descriptive name that we could use here? Maybe something like `buildFromHeader` (to indicate that pulls configuration data from the plugin/theme header)?

Yes, I agree completely, but I couldn't really think of a name.  Now renamed to `buildFromHeader`.
 
> Also, I'd like to add the `EXTR_SKIP` flag to that `extract($args)` call. Technically, it's currently not necessary since the array is already filtered with `array_intersect_key`, but it could help prevent future bugs if the method becomes more complex over time.

Added.  `$fullPath` is the only variable that might be affected - for now at least.

**Comment by abuyoyo** [comment]
> I feel like the method name updateChecker is too generic and it could be easily confused with buildUpdateChecker. Is there are a more descriptive name that we could use here?

Would not point of this be to have an API that _is_ a fully-functioning alternative to `buildUpdateChecker`?
That can be used whether on not plugin header fallbacks exist? ie. `plugin_uri` arg would only be omitted from the args array if a relevant plugin header is provided.

**Comment by RichardCoffee** [comment]
> Would not point of this be to have an API that _is_ a fully-functioning alternative to `buildUpdateChecker`?
> That can be used whether on not plugin header fallbacks exist? ie. `plugin_uri` arg would only be omitted from the args array if a relevant plugin header is provided.

Yes, exactly.  Currently the method will only look for the uri if it has not been passed in the args array.

**Comment by abuyoyo** [comment]
I was referencing the API method naming decision.
The way I see it the `($filename, $args_array)` method _should_ be generic. ie. on par with `buildUpdateChecker`. There is no reason to limit it to something like `buildFromHeader`. That would suggest the method only works if the user sets the repo uri in the plugin header. Which is not the case.

**Comment by YahnisElsts** [comment]
Whether the method itself is generic or not, I think having two methods with very similar names would still be a bad idea.

**Comment by abuyoyo** [comment]
I understand that design decision.
How about `simpleUpdateCheckerBuilder` or `simplifiedUpdateChecker`. Different enough to not cause confusion. But without implying its only used with plugin headers.

**Pull request merged**
