### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by LDAV**
[plugin-update-checker-it_IT.zip](https://github.com/YahnisElsts/plugin-update-checker/files/706563/plugin-update-checker-it_IT.zip)

### CODE REVIEW

**Comment by YahnisElsts** [comment]
Could you please also include the .mo file in the pull request? I know I could copy it from the ZIP file myself and then commit it later, but it seems cleaner to merge both files in one go.

**Comment by LDAV** [comment]
Uploads are disabled for me.
"File uploads require push access to this repository".

**Comment by YahnisElsts** [comment]
If I understand correctly, you don't need to upload anything. Just push the file to your `patch-1` branch.

**Comment by LDAV** [comment]
ok

**Comment by YahnisElsts** [comment]
Hmm, did you intend to close the pull request? I don't think it will get updated with your changes if it's closed.

**Comment by LDAV** [comment]
hope it works

**Comment by YahnisElsts** [comment]
Looks good. Thank you, I'll merge it now.

**Pull request merged**
