### PR TITLE
Support languages

### PR DESCRIPTION
**Pull request by icetee**
Translation beinning

### CODE REVIEW

**Comment by YahnisElsts** [comment]
I'm a bit sick at the moment, but I promise I'll look into this when I get the chance.

There's one thing that I will state right away: **Please don't localize error messages that target developers.** 

Translating them makes it impossible to Google the errors. That's very bad. It also makes it harder for me to help people who use this library - if someone asks me how to fix an error that their running into and the error is in a language that I don't speak, it will be much harder to figure out what the problem is.

Additional discussion:
- http://stackoverflow.com/questions/209133/c-sharp-exception-messages-in-english
- http://stackoverflow.com/questions/929604/should-exception-messages-that-are-targeted-to-the-developer-be-localized

**Comment by YahnisElsts** [comment]
I've reviewed the changes more carefully. It looks like there are:

- 12 translated exceptions, error messages or debugging messages - text that would be seen by developers.
- 8 translated UI strings - text that would be seen by users.
- A huge number of whitespace changes that clutter the diff's.

That's not great. While translating UI text like links and status messages is a pretty good idea, I'm not willing to accept the rest of the changes.

**Comment by YahnisElsts** [comment]
Any thoughts?

**Comment by icetee** [comment]
I agree. But I think it would certainly be nice if the UI strings could be translate, because the WordPress itself is multilingual.

**Comment by icetee** [comment]
Do I change it to just change the UI variables?

**Comment by YahnisElsts** [comment]
Yes, I think that would be best. 

Also, it might be a good idea to change the text domain to something unique. There are other update checkers out there, so there's a chance of name collisions if we use a general phrase like `plugin-update-checker`.

**Comment by icetee** [comment]
Please check the "Support i18n" commit.

**Comment by YahnisElsts** [comment]
Looks good. Have you tested it with the latest WP release (4.4.1)?

**Comment by YahnisElsts** [comment]
Never mind, I tested it myself. It works.

**Pull request merged**
