### PR TITLE
Add GiTea compatibility

### PR DESCRIPTION
**Pull request by DjSni**

### CODE REVIEW

**Comment by YahnisElsts** [comment]
I'm not familiar with GiTea so I have some questions:

- How *does* GiTea handle releases and release assets? I see that there's a comment about it not being the same as GitHub. Does it still make sense to use the latest release if it's available?
- Do the archive download URLs for tags, branches, and releases all follow the same format? 
- Is authentication based on a simple token like in the current implementation, or will something more complex be needed?
- How much testing have you done so far/how stable is this implementation? Could I try using it with my own GiTea repository if I had one?

**Comment by DjSni** [comment]
gladly.

- Yes it is different, the current stable version is 1.8.3 the API unfortunately does not offer some things there yet. Currently there is a 1.9.0rc2 and the 1.10-dev so I wait until the 1.9.0 is stable to continue.
- Yes except when using release assets
- This is a little bit easier than with GitHub, here you have unfortunately only one token and this has all right
- Currently only tags work, the rest I'm still working on or waiting for a new version of the API. Yes you can try it with your own server or gitea.com account (uses the current 1.10-dev version).

**Comment by DjSni** [comment]
It seems that there are a lot of bugs in the API of GiTea that have to be fixed before I can finish the interface.

greetings

**Comment by mcnaveen** [comment]
It's still WIP?

**Pull request closed without merging**
